package com.sunbeam.entities;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.OneToMany;

import java.util.HashSet;
import java.util.Set;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Table(name = "wishlists")
@Getter
@Setter
@NoArgsConstructor
public class WishList {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "wishlist_id")
    private Long id;

    @OneToOne(fetch = FetchType.EAGER, optional = false)
    @JoinColumn(name = "user_id")
    private User user;

    @OneToMany(mappedBy = "wishlist", cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    private Set<WishListItem> items = new HashSet<>();

    // Add any additional fields or methods related to WishList

    // Constructor, getters, and setters can be automatically generated by Lombok

    // Example method to add an item to the wishlist
    public void addItem(WishListItem item) {
//    	if (item == null) {
//            throw new IllegalArgumentException("Item cannot be null");
//        }
//        this.items.add(item);
//        item.setWishlist(this);
        
        this.items.add(item);
		
//		wishListItem.setWishlist(this);
        item.setWishlist(this);
        
        
    }

    // Example method to remove an item from the wishlist
    public void removeItem(WishListItem item) {
        this.items.remove(item);
        item.setWishlist(null);
    }

    // Example method to get the total number of items in the wishlist
    public int getItemCount() {
        return this.items.size();
    }
}
